version: '3.1'
volumes:
  horreum_pg12: {}
services:
  postgres:
    image: docker.io/postgres:12
    env_file: postgres.env
    network_mode: host
    environment:
    - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    - PG_PORT=${POSTGRES_PORT:-5432}
    # due to https://docs.docker.com/compose/compose-file/compose-file-v3/#ports ports being mutually exclusive
    # this breaks running the test suite in conjunction with Quarkus dev mode.
  # port here is not compatible with docker-compose. However it is necessary when using podman-compose v0.7.3 to
  # to start infrastructure containers.
#    port:
 #     - "5432:5432"
    volumes:
    - horreum_pg12:/var/lib/postgresql/data
  db-init:
    depends_on:
    - postgres
    image: docker.io/postgres:12
    restart: on-failure
    env_file: postgres.env
    environment:
    - PGHOST=${CONTAINER_HOST_IP:-localhost}
    - PGPORT=${POSTGRES_PORT:-5432}
    volumes:
    - ../:/cwd:ro,z
    command:
    - bash
    - -x
    - /cwd/infra/create-db.sh
    network_mode: host
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    depends_on:
    - postgres
    environment:
    - KC_HTTP_HOST=127.0.0.1
    - EXTRA_OPTIONS=-Djboss.bind.address=0.0.0.0 -Djboss.bind.address.private=127.0.0.1
    - DB_ADDR=${CONTAINER_HOST_IP:-localhost}
    - DB_PORT=${POSTGRES_PORT:-5432}
    network_mode: host
    volumes:
    - ../:/cwd:rw,z
  app-init:
    depends_on:
    - keycloak
    image: docker.io/dwdraju/alpine-curl-jq
    restart: on-failure
    command:
    - bash
    - -x
    - /cwd/infra/app-init.sh
    environment:
    - POSTGRES_HOST=${CONTAINER_HOST_IP:-localhost}
    - KEYCLOAK_HOST=${CONTAINER_HOST_IP:-localhost}
    network_mode: host
    volumes:
    - ../:/cwd:rw,z
  grafana:
    depends_on:
    - keycloak
    - app-init
    image: grafana/grafana
    entrypoint: /cwd/infra/grafana.sh
    env_file: grafana.env
    network_mode: host
    user: "0:0"
    volumes:
    - ../:/cwd:ro,z
